
// This file has been generated by the GUI designer. Do not modify.
namespace DesktopAPP_APIPOST
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action TeenvioAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action helpAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Action ContactsAction;
		private global::Gtk.Action ListAction;
		private global::Gtk.Action GroupsAction;
		private global::Gtk.Action ImportAction;
		private global::Gtk.Action CampaingsAction;
		private global::Gtk.Action ListAction1;
		private global::Gtk.Action NewAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label3;
		private global::Gtk.ComboBox comboCampaigns;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblTableTitle;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView nodeviewTable;
		private global::Gtk.Statusbar statusbar1;
		private global::Gtk.Label lblState;
		private global::Gtk.Label lblStatusBarVersion;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DesktopAPP_APIPOST.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.TeenvioAction = new global::Gtk.Action ("TeenvioAction", global::Mono.Unix.Catalog.GetString ("_Teenvio"), null, null);
			this.TeenvioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Teenvio");
			w1.Add (this.TeenvioAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
			w1.Add (this.HelpAction, null);
			this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-help");
			this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.helpAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
			w1.Add (this.quitAction, null);
			this.ContactsAction = new global::Gtk.Action ("ContactsAction", global::Mono.Unix.Catalog.GetString ("_Contacts"), null, null);
			this.ContactsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Contacts");
			w1.Add (this.ContactsAction, null);
			this.ListAction = new global::Gtk.Action ("ListAction", global::Mono.Unix.Catalog.GetString ("List"), null, null);
			this.ListAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("List");
			w1.Add (this.ListAction, null);
			this.GroupsAction = new global::Gtk.Action ("GroupsAction", global::Mono.Unix.Catalog.GetString ("Groups"), null, null);
			this.GroupsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Groups");
			w1.Add (this.GroupsAction, null);
			this.ImportAction = new global::Gtk.Action ("ImportAction", global::Mono.Unix.Catalog.GetString ("Import"), null, null);
			this.ImportAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import");
			w1.Add (this.ImportAction, null);
			this.CampaingsAction = new global::Gtk.Action ("CampaingsAction", global::Mono.Unix.Catalog.GetString ("Ca_mpaings"), null, null);
			this.CampaingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ca_mpaings");
			w1.Add (this.CampaingsAction, null);
			this.ListAction1 = new global::Gtk.Action ("ListAction1", global::Mono.Unix.Catalog.GetString ("List"), null, null);
			this.ListAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("List");
			w1.Add (this.ListAction1, null);
			this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
			this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
			w1.Add (this.NewAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "DesktopAPP_APIPOST.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Teenvio");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child DesktopAPP_APIPOST.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='TeenvioAction' action='TeenvioAction'><menuitem name='quitAction' action='quitAction'/></menu><menu name='ContactsAction' action='ContactsAction'><menuitem name='ListAction' action='ListAction'/><menuitem name='GroupsAction' action='GroupsAction'/><menuitem name='ImportAction' action='ImportAction'/></menu><menu name='CampaingsAction' action='CampaingsAction'><menuitem name='ListAction1' action='ListAction1'/><menuitem name='NewAction' action='NewAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(12));
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Last Campaigns");
			this.vbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.comboCampaigns = global::Gtk.ComboBox.NewText ();
			this.comboCampaigns.Name = "comboCampaigns";
			this.vbox3.Add (this.comboCampaigns);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.comboCampaigns]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w5.Position = 0;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblTableTitle = new global::Gtk.Label ();
			this.lblTableTitle.Name = "lblTableTitle";
			this.lblTableTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Table");
			this.vbox4.Add (this.lblTableTitle);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblTableTitle]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeviewTable = new global::Gtk.NodeView ();
			this.nodeviewTable.CanFocus = true;
			this.nodeviewTable.Name = "nodeviewTable";
			this.GtkScrolledWindow.Add (this.nodeviewTable);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w9.Position = 1;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w10.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w11.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.statusbar1.BorderWidth = ((uint)(1));
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblState = new global::Gtk.Label ();
			this.lblState.Name = "lblState";
			this.lblState.Xalign = 0F;
			this.lblState.LabelProp = global::Mono.Unix.Catalog.GetString ("Ready");
			this.statusbar1.Add (this.lblState);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblState]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.lblStatusBarVersion = new global::Gtk.Label ();
			this.lblStatusBarVersion.Name = "lblStatusBarVersion";
			this.lblStatusBarVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("Version:");
			this.statusbar1.Add (this.lblStatusBarVersion);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblStatusBarVersion]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(1));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 607;
			this.DefaultHeight = 432;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
			this.ListAction1.Activated += new global::System.EventHandler (this.OnListAction1Activated);
		}
	}
}
