
// This file has been generated by the GUI designer. Do not modify.
public partial class LoginWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Table table1;
	private global::Gtk.Button btnEnter;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Entry txtPassword;
	private global::Gtk.Entry txtPlan;
	private global::Gtk.Entry txtUser;
	private global::Gtk.Image image1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget LoginWindow
		this.Name = "LoginWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("TeenvioDesktop");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child LoginWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.btnEnter = new global::Gtk.Button ();
		this.btnEnter.CanFocus = true;
		this.btnEnter.Name = "btnEnter";
		this.btnEnter.UseUnderline = true;
		this.btnEnter.Label = global::Mono.Unix.Catalog.GetString ("_Enter");
		this.table1.Add (this.btnEnter);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnEnter]));
		w1.TopAttach = ((uint)(3));
		w1.BottomAttach = ((uint)(4));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("User");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Plan/Acount");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtPassword = new global::Gtk.Entry ();
		this.txtPassword.CanFocus = true;
		this.txtPassword.Name = "txtPassword";
		this.txtPassword.IsEditable = true;
		this.txtPassword.Visibility = false;
		this.txtPassword.InvisibleChar = '●';
		this.table1.Add (this.txtPassword);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPassword]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtPlan = new global::Gtk.Entry ();
		this.txtPlan.CanFocus = true;
		this.txtPlan.Name = "txtPlan";
		this.txtPlan.IsEditable = true;
		this.txtPlan.InvisibleChar = '●';
		this.table1.Add (this.txtPlan);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPlan]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtUser = new global::Gtk.Entry ();
		this.txtUser.CanFocus = true;
		this.txtUser.Name = "txtUser";
		this.txtUser.IsEditable = true;
		this.txtUser.InvisibleChar = '●';
		this.table1.Add (this.txtUser);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtUser]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add (this.table1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.table1]));
		w8.X = 214;
		w8.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icono_teenvio.png"));
		this.fixed1.Add (this.image1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image1]));
		w9.X = 70;
		w9.Y = 74;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 612;
		this.DefaultHeight = 260;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnEnter.Clicked += new global::System.EventHandler (this.btnEnter_Click);
	}
}
