// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_APIPOST {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.TextBox textBox1;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.WebControls.TextBox textBox2;
		
		protected System.Web.UI.WebControls.Button button3;
		
		protected System.Web.UI.WebControls.TextBox textBox3;
		
		protected System.Web.UI.WebControls.Button button4;
		
		protected System.Web.UI.WebControls.ListBox listBox1;
		
		protected System.Web.UI.WebControls.TreeView treeView1;
		
		protected System.Web.UI.WebControls.Button button5;
		
		protected System.Web.UI.WebControls.TextBox textBox5;
	}
}
